import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, Check, MoveRight } from "lucide-react";
import LiquidGlassPanel from "@/components/liquid-glass/LiquidGlassPanel";
import { getImageBrief } from "@/lib/image-manifest";

const imageSet = {
  hero: getImageBrief("home.hero")!.source,
  machine: getImageBrief("product.rotavator")!.source,
  workshop: getImageBrief("home.workshop")!.source,
  field: getImageBrief("home.application")!.source,
  detail: "/visuals/detail.jpg",
};
const machines = [
  { index: "01", type: "Soil preparation", name: "Multi-Speed\nRotavator", image: imageSet.machine },
  { index: "02", type: "Field precision", name: "Laser Land\nLeveller", image: imageSet.field },
  { index: "03", type: "Crop processing", name: "Multi-Crop\nThresher", image: imageSet.detail },
];
const disciplines = ["Agricultural machinery", "Custom fabrication", "Field engineering", "After-sales support"];

export default function HomePage() {
  return <main className="new-home">
    <section className="new-hero"><Image src={imageSet.hero} alt="Agricultural field and working machinery" fill priority sizes="100vw" className="cover-image" /><div className="hero-vignette" /><div className="shell hero-layout"><div className="hero-copy-new"><p className="eyebrow light">01 / Agricultural engineering</p><h1>Machines<br /><i>shaped</i> around<br />the field.</h1><p className="hero-intro">RAEW builds practical agricultural machinery and custom engineering solutions for the conditions that matter: real soil, real seasons, real work.</p><div className="hero-links"><Link href="/products" className="glass-button">Explore machinery <ArrowUpRight size={16} /></Link><Link href="#story" className="quiet-link">Scroll to explore <ArrowDown size={15} /></Link></div></div><LiquidGlassPanel className="hero-spec"><p className="eyebrow light">RAEW / 001</p><p className="spec-title">Engineering<br />for the field</p><div className="spec-rule" /><p className="spec-meta">Mirzapur, Uttar Pradesh<br />India</p></LiquidGlassPanel></div><div className="hero-index">Scroll to discover <span>↓</span></div></section>
    <section className="statement-section" id="story"><div className="shell statement-layout"><p className="eyebrow">02 / The RAEW approach</p><div><h2>We don&apos;t build<br /><span>more machine.</span></h2><p className="statement-copy">We build the right machine. Every requirement starts with the ground it must work on, the crop it must handle and the people who will operate it.</p><Link className="arrow-link" href="/about">Meet the engineering team <MoveRight size={18} /></Link></div></div></section>
    <section className="founder-section"><div className="shell founder-layout"><div className="founder-portrait"><Image src="/images/company/founder-rajnand-tiwari.png" alt="Mr. Rajnand Tiwari, Founder of M/s Raj Agro Engineering Works" fill sizes="(max-width: 800px) 100vw, 42vw" className="founder-image" /></div><div className="founder-copy"><p className="eyebrow">03 / Leadership</p><h2>Meet Our<br /><i>Founder</i></h2><p className="founder-subtitle">Leadership rooted in experience, integrity, and engineering excellence.</p><div className="founder-badge">Founder</div><h3>Mr. Rajnand Tiwari</h3><p className="founder-role">Founder, M/s Raj Agro Engineering Works</p><div className="founder-bio"><p>Mr. Rajnand Tiwari is the Founder of M/s Raj Agro Engineering Works, a company built around engineering expertise, dependable workmanship, and a commitment to delivering practical solutions for industrial and agricultural requirements. Through his leadership and vision, RAEW has developed its capabilities across engineering fabrication, agricultural machinery, industrial solutions, and project execution.</p><p>His approach emphasizes quality, reliability, customer trust, and long-term relationships. His vision continues to guide RAEW toward sustainable growth, modern engineering practices, and consistently high standards of execution.</p></div><p className="founder-quote">“Building with integrity, engineering with purpose, and growing through trust.”</p></div></div></section>
    <section className="machine-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow light">04 / The working catalogue</p><h2>Made to<br /><i>move.</i></h2></div><p>Three examples from a wider catalogue of field-ready machines. Choose a platform, then make it yours.</p></div><div className="machine-grid">{machines.map((machine) => <Link href="/products" className="machine-card" key={machine.index}><div className="machine-image"><Image src={machine.image} alt={machine.name.replace("\n", " ")} fill sizes="(max-width: 768px) 100vw, 33vw" className="cover-image" /><span>{machine.index}</span></div><div className="machine-card-body"><p className="eyebrow light">{machine.type}</p><h3>{machine.name.split("\n").map((line) => <span key={line}>{line}</span>)}</h3><span className="card-arrow"><ArrowUpRight size={18} /></span></div></Link>)}</div><div className="section-cta"><Link className="arrow-link light-link" href="/products">View the full catalogue <MoveRight size={18} /></Link></div></div></section>
    <section className="process-section-new"><div className="shell process-layout"><div className="process-intro"><p className="eyebrow">04 / How we make</p><h2>From first<br /><i>question</i><br />to final bolt.</h2><p>Good engineering is a sequence of decisions. We keep the sequence visible.</p></div><div className="process-list">{["Listen", "Design", "Fabricate", "Prove"].map((step, index) => <div className="process-row" key={step}><span>0{index + 1}</span><h3>{step}</h3><p>{["Understand the crop, tractor, soil and operator.", "Turn a requirement into a machine that can be built and maintained.", "Cut, weld, machine and assemble with purpose.", "Inspect, refine and send it into the work it was made for."][index]}</p><MoveRight size={19} /></div>)}</div></div></section>
    <section className="workshop-section"><Image src={imageSet.workshop} alt="Industrial metal fabrication workshop" fill sizes="100vw" className="cover-image" /><div className="workshop-shade" /><div className="shell workshop-content"><p className="eyebrow light">05 / Behind the build</p><h2>Built with<br /><i>discipline.</i></h2><p>Fabrication is where an idea earns its weight. Our work is grounded in material, tolerances and the everyday reality of maintenance.</p><Link href="/manufacturing" className="glass-button">Inside the workshop <ArrowUpRight size={16} /></Link></div></section>
    <section className="application-section"><div className="shell"><div className="application-top"><p className="eyebrow">06 / Where it works</p><h2>One machine.<br /><span>Many seasons.</span></h2></div><div className="application-grid"><div className="application-feature"><Image src={imageSet.field} alt="Machine work in an agricultural field" fill sizes="(max-width: 768px) 100vw, 55vw" className="cover-image" /><div><p className="eyebrow light">Field application / 01</p><h3>Prepare better.<br />Plant with confidence.</h3></div></div><div className="application-notes">{disciplines.map((discipline, index) => <div key={discipline}><span>0{index + 1}</span><p>{discipline}</p><Check size={17} /></div>)}</div></div></div></section>
    <section className="custom-section-new"><div className="shell custom-layout"><div><p className="eyebrow light">07 / Custom engineering</p><h2>Your field<br /><i>isn&apos;t standard.</i></h2><p>Tell us what the catalogue cannot. A width, a crop, a constraint, a better way of doing the work.</p></div><LiquidGlassPanel className="custom-panel"><p className="eyebrow light">Start with a requirement</p><h3>Let&apos;s shape<br />the brief.</h3><Link href="/quote" className="glass-button">Request a quote <ArrowUpRight size={16} /></Link></LiquidGlassPanel></div></section>
    <section className="projects-section"><div className="shell"><div className="section-heading projects-heading"><div><p className="eyebrow">08 / Selected work</p><h2>Out in<br /><i>the world.</i></h2></div><Link className="arrow-link" href="/projects">See all projects <MoveRight size={18} /></Link></div><div className="project-gallery"><Link href="/projects" className="project-large"><Image src={imageSet.detail} alt="Agricultural implement working outdoors" fill sizes="(max-width: 768px) 100vw, 65vw" className="cover-image" /><div><p className="eyebrow light">Project / 001</p><h3>Designed for<br />the long run.</h3></div></Link><Link href="/gallery" className="project-small"><Image src={imageSet.machine} alt="Close detail of agricultural machinery" fill sizes="(max-width: 768px) 100vw, 35vw" className="cover-image" /><div><p className="eyebrow light">Field notes ↗</p></div></Link></div></div></section>
    <section className="quote-section"><div className="shell quote-layout"><p className="eyebrow">09 / The next move</p><h2>Let&apos;s build<br /><i>something useful.</i></h2><Link href="/quote" className="outline-button">Start a conversation <ArrowUpRight size={17} /></Link></div></section>
  </main>;
}
